//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTiers.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SchoolEntities : DbContext
    {
        public SchoolEntities()
            : base("name=SchoolEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Course> Courses { get; set; }
        public virtual DbSet<Enrollment> Enrollments { get; set; }
        public virtual DbSet<Instructor> Instructors { get; set; }
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual int Courses_AddCourse(Nullable<int> courseID, string courseName, string courseDesc, Nullable<int> courseInst)
        {
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            var courseNameParameter = courseName != null ?
                new ObjectParameter("CourseName", courseName) :
                new ObjectParameter("CourseName", typeof(string));
    
            var courseDescParameter = courseDesc != null ?
                new ObjectParameter("CourseDesc", courseDesc) :
                new ObjectParameter("CourseDesc", typeof(string));
    
            var courseInstParameter = courseInst.HasValue ?
                new ObjectParameter("CourseInst", courseInst) :
                new ObjectParameter("CourseInst", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Courses_AddCourse", courseIDParameter, courseNameParameter, courseDescParameter, courseInstParameter);
        }
    
        public virtual int Students_UpdateStudent(Nullable<int> stdID, string stdName)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            var stdNameParameter = stdName != null ?
                new ObjectParameter("stdName", stdName) :
                new ObjectParameter("stdName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Students_UpdateStudent", stdIDParameter, stdNameParameter);
        }
    
        public virtual int Students_RemoveStudent(Nullable<int> stdID)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Students_RemoveStudent", stdIDParameter);
        }
    
        public virtual int Students_AddStudent(Nullable<int> stdID, string stdName)
        {
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            var stdNameParameter = stdName != null ?
                new ObjectParameter("stdName", stdName) :
                new ObjectParameter("stdName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Students_AddStudent", stdIDParameter, stdNameParameter);
        }
    
        public virtual int Instructors_UpdateInstructor(Nullable<int> instID, string instName)
        {
            var instIDParameter = instID.HasValue ?
                new ObjectParameter("InstID", instID) :
                new ObjectParameter("InstID", typeof(int));
    
            var instNameParameter = instName != null ?
                new ObjectParameter("InstName", instName) :
                new ObjectParameter("InstName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Instructors_UpdateInstructor", instIDParameter, instNameParameter);
        }
    
        public virtual int Instructors_RemoveInstructor(Nullable<int> instID)
        {
            var instIDParameter = instID.HasValue ?
                new ObjectParameter("InstID", instID) :
                new ObjectParameter("InstID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Instructors_RemoveInstructor", instIDParameter);
        }
    
        public virtual int Courses_RemoveCourse(Nullable<int> courseID)
        {
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Courses_RemoveCourse", courseIDParameter);
        }
    
        public virtual int Courses_UpdateCourse(Nullable<int> courseID, string courseName, string courseDesc, Nullable<int> courseInst)
        {
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            var courseNameParameter = courseName != null ?
                new ObjectParameter("CourseName", courseName) :
                new ObjectParameter("CourseName", typeof(string));
    
            var courseDescParameter = courseDesc != null ?
                new ObjectParameter("CourseDesc", courseDesc) :
                new ObjectParameter("CourseDesc", typeof(string));
    
            var courseInstParameter = courseInst.HasValue ?
                new ObjectParameter("CourseInst", courseInst) :
                new ObjectParameter("CourseInst", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Courses_UpdateCourse", courseIDParameter, courseNameParameter, courseDescParameter, courseInstParameter);
        }
    
        public virtual int Enrollments_AddEnrollment(Nullable<int> courseID, Nullable<int> stdID)
        {
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Enrollments_AddEnrollment", courseIDParameter, stdIDParameter);
        }
    
        public virtual int Enrollments_RemoveEnrollment(Nullable<int> enrollID)
        {
            var enrollIDParameter = enrollID.HasValue ?
                new ObjectParameter("EnrollID", enrollID) :
                new ObjectParameter("EnrollID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Enrollments_RemoveEnrollment", enrollIDParameter);
        }
    
        public virtual int Enrollments_UpdateEnrollment(Nullable<int> enrollID, Nullable<int> courseID, Nullable<int> stdID)
        {
            var enrollIDParameter = enrollID.HasValue ?
                new ObjectParameter("EnrollID", enrollID) :
                new ObjectParameter("EnrollID", typeof(int));
    
            var courseIDParameter = courseID.HasValue ?
                new ObjectParameter("CourseID", courseID) :
                new ObjectParameter("CourseID", typeof(int));
    
            var stdIDParameter = stdID.HasValue ?
                new ObjectParameter("stdID", stdID) :
                new ObjectParameter("stdID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Enrollments_UpdateEnrollment", enrollIDParameter, courseIDParameter, stdIDParameter);
        }
    
        public virtual int Instrucors_AddInstructor(Nullable<int> instID, string instName)
        {
            var instIDParameter = instID.HasValue ?
                new ObjectParameter("InstID", instID) :
                new ObjectParameter("InstID", typeof(int));
    
            var instNameParameter = instName != null ?
                new ObjectParameter("InstName", instName) :
                new ObjectParameter("InstName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("Instrucors_AddInstructor", instIDParameter, instNameParameter);
        }
    }
}
